all: review_test.o excurcao_test.o session_test.o user_test.o

review_test.o: review_test.cpp review_test.hpp
	g++ -std=c++17 -Wall -c review_test.cpp

excurcao_test.o: excurcao_test.cpp excurcao_test.hpp
	g++ -std=c++17 -Wall -c excurcao_test.cpp

session_test.o: session_test.cpp session_test.hpp
	g++ -std=c++17 -Wall -c session_test.cpp

user_test.o: user_test.cpp user_test.hpp
	g++ -std=c++17 -Wall -c user_test.cpp
