all: review.o excurcao.o session.o user.o

review.o: review.cpp review.hpp
	g++ -std=c++17 -Wall -c review.cpp

excurcao.o: excurcao.cpp excurcao.hpp
	g++ -std=c++17 -Wall -c excurcao.cpp

session.o: session.cpp session.hpp
	g++ -std=c++17 -Wall -c session.cpp


user.o: user.cpp user.hpp
	g++ -std=c++17 -Wall -c user.cpp
